### ISSUE TITLE
RemoveRow doesn´t work when rowReorder is set to true 

### ISSUE THREAD

**Issue by thailakadre** [atatanasov/gijgo#109]
If I changed the attribute "rowReorder" to false then It´s possible delete a row. But It both together doesn´t work.

Code: 
function DeleteApprover(e) {
		 if (confirm('Deseja deletar?')) {
			 gridApprovers.removeRow(e.data.id);
		 }
	 }
 
$(document).ready(function () {
 gridApprovers = $('#gridApprovers').grid({
				 primaryKey: 'ID',
				 uiLibrary: 'bootstrap',
				 responsive: false,
				 rowReorder: true,
				 orderNumberField: 'Order',
				 columns: [
					 { field: 'ID', hidden: true },
					 { field: 'Order', hidden: false },
					 { field: 'Name', title: 'Nome', priority: 1 },
					 { title: '', width: 34, type: 'icon', icon: 'glyphicon-remove', tooltip: 'Delete', events: { 'click': DeleteApprover }}
				 ]
			 });
 });

**Comment by atatanasov** [comment]
everything works fine during my testing. You can see my sample at http://gijgo.com/Temp/29652c1a-e0eb-4f39-b840-4d0e12e93558.html

In your sample code there is no dataSource, when I add dataSource setting everything seems to be fine.

**Comment by thailakadre** [comment]
But In your example the row reorder isn´t working.

**Comment by thailakadre** [comment]
http://gijgo.com/LiveEdit/Index/ajax-sourced-data.html?component=grid# I added this to attibutes from this example too and it didn´t work. 

```
	 **rowReorder: true,
				 orderNumberField: 'ID',**
```

**Comment by atatanasov** [comment]
The row reordering doesn't work, because draggable.js and droppable.js are not included. I think that would be best for you if you user http://gijgo.com/grid/configuration/rowReorderColumn in order to specify only one column where the dragging for reorder is enabled. If you not specify rowReorderColumn you can't delete row, because the grid is handle the click as attemp for reorder via delete column/cell. You can see my working example at:

http://gijgo.com/Temp/351ed16f-629e-4b0d-ae87-a5aeede57f26.html
