### ISSUE TITLE
Conflict with https://github.com/uxsolutions/bootstrap-datepicker

### ISSUE THREAD

**Issue by bimalingit** [atatanasov/gijgo#128]
I am using the [bootstrap-datepicker from uxsolutions](https://github.com/uxsolutions/bootstrap-datepicker) as well as the gijgo combined library

Both the libraries define the method 'datepicker' for creating the datepicker and they are conflicting with each other.

For the time being, i have renamed the methods from gijgo library but this conflict needs to be taken care of so that both the libraries can be used simultaneously

**Comment by atatanasov** [comment]
Hello,

This is known issue when you use the combined build. In order to fix it you have to use the modular build that is located at https://github.com/atatanasov/gijgo/tree/master/dist/modular.
If you use modular build you have include core.css and core.js + js and css file for every gijgo component that is in use by your project.

Side: What is the advantages of the datepicker from uxsolutions compared to our datepicker? What we need to add to our datepicker in order use our datepicker instead of the other?
