### ISSUE TITLE
Datepicker - renaming

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#138]
Dear Mr. Atanasov, would you please choose an other name for the plugin function 'datepicker'....e.g. 'dateselect' or 'datechooser' as soon as possible?

There are other Jquery Datepicker plugins in the net with more features/ options than the Gijgo Datepicker.
I would like use [Bootstrap Datepicker](http://bootstrap-datepicker.readthedocs.io/en/latest/) in my dialogs without conflict together with Gijgo 1.5 .

**Comment by atatanasov** [comment]
We can't rename this widget, because that's how a lot of other people and projects want it.
You have 2 options to resolve this:
1. You can use modular build of gijgo and include only the widgets that you want to use. Here is an example https://github.com/atatanasov/gijgo/blob/master/examples/grid/Grid.Base.getSelections.With.Primary.Ket.html
2. You can include your datepicker.js after the gijgo.js and the datepicker.js have to override the datepicker in the gijgo.js

I changed the code in the new development version to define gijgo jquery widget only if there is no other definition of jquery widget with the same name.

We are also working in a direction to add new features in our datepicker and make it better that the other datepickers on the market.
