### ISSUE TITLE
DatePicker issue

### ISSUE THREAD

**Issue by aimi617** [atatanasov/gijgo#189]
In our mvc project we use bootstrap 3, jquery-ui-1.12.1 Datepicker with gijgo 1.5.1, after upgrading to 1.6.0, all jquery-ui datepicker fields stopped working completely crashing project.

Somehow version 1.6.0 causes a conflict with a  jquery-ui Datepicker. Is it possible to isolate gijgo Datepicker from Datepicker widget in jquery-ui-1.12.1?

**Comment by atatanasov** [comment]
gijgo.js needs to be before jqueryui.js in order to allow jquery ui datepicker to override gijgo datepicker. gijgo.js is after jquery ui, than gijgo override everything. You can also use modular build (https://github.com/atatanasov/gijgo/tree/master/dist/modular) where you can include only the widgets that you need.

**Comment by aimi617** [comment]
Thanks, it resolved an issue. We also tried a modular build but couldn't find a sample how to use it. Changing the path from "combined" to "modular" and referencing grid.js doesn't show a grid at all, also tried to add a reference to checkbox.js, core.js and grid.js, same situation, grid doesn't show up.

**Comment by aimi617** [comment]
Issue has been resolved, it was a wrong reference to grid.js, now grid does show up using modular build.

**Comment by atatanasov** [comment]
Great! Happy coding...
