### ISSUE TITLE
Editor - should it work with a textarea

### ISSUE THREAD

**Issue by thepurpleblob** [atatanasov/gijgo#235]
Possibly I'm missing the point, but the editor doesn't seem to work with textareas (like TinyMCE, Summernote and so on). 

I tried it, and it applied various classes to the textarea but doesn't show menu bar and so on. 

Without writing lots of extra javascript, I'm unsure how the editor is useful if it can't be applied to a form control.

(example here - http://gijgo.com/editor - uses a div)

**Comment by atatanasov** [comment]
None of them is actually based on textarea. TinyMCE is based on iframe and summernote is based on div with attribute contenteditable=true. Gijgo editor is also based on div with attribute contenteditable=true which is considered the most effective and modern approach. You can inspect the html code behind each editor in order to confirm that. I decided to not hide the reality and that's why my examples are using div tags.

**Comment by thepurpleblob** [comment]
Yes I know, but it's not really my point (sorry if I wasn't clear). They end up with the text back in a textarea which will be submitted as part of a form. With gijgo one needs to do a bit of work to grab the editor data. 

It's not the end of the world. I really like the gijgo stuff and was converting my forms from TinyMCE.

**Comment by atatanasov** [comment]
I see what you mean. We are going to improve this in the future and add support of textareas as well.

**Comment by atatanasov** [comment]
We imporved that. You can use the editor with textares in the new development build in the dist folder at github.

**Comment by stvowi** [comment]
very fine
