### ISSUE TITLE
RENDER Problem in Tree

### ISSUE THREAD

**Issue by jubairmpower** [atatanasov/gijgo#237]
when try to render a tree with thousands of nodes , it slows down and takes a lot of time to render, sometimes shows time out.

**Comment by atatanasov** [comment]
Could you tell me the exact number of nodes that you are trying to use. Can you provide a sample json file that I can use for testing?

Did you try to use our lazy loading configuration setting that is design for such cases?

**Comment by jubairmpower** [comment]
Actually I did not try lazy loading yet, as there are many dependency in my app...It will be convenient to load whole data for me.
I can attach you a test json but the fact is for my purpose it can be much more larger
[testjson.txt](https://github.com/atatanasov/gijgo/files/1631134/testjson.txt)

**Comment by atatanasov** [comment]
The file that you send is broken. The json is not formatted correcty. You can go to the end of the file in order to see that. Everything works fine with fixed json. You can see my fix for your file in the attachment.
[json-repaired.txt](https://github.com/atatanasov/gijgo/files/1691875/json-repaired.txt)
