### ISSUE TITLE
Row id

### ISSUE THREAD

**Issue by mmanna3** [atatanasov/gijgo#285]
Hi, I would like to know if there is a way to access the row ID of a grid from the template block.
Thanks in advance.

**Comment by atatanasov** [comment]
Yes. You can find the id as parameter in the detailExpand and detailCollapse events. Here is the documentation:
http://gijgo.com/grid/events/detailExpand
http://gijgo.com/grid/events/detailCollapse

Here is another example of that functionality:
http://gijgo.com/grid/demos/nested-jquery-grids

Is that what you need?

**Comment by mmanna3** [comment]
I believe I'm not explaining myself rightly. Sorry, my english is not as good as I'd like.

In the grid template, I have a dropdown button that contains links. But I need to insert the row id as a parameter of those links. For example, one of those links could be http://mypage.com/?id= **[rowId]**.

**Comment by atatanasov** [comment]
You can use our column.renderer configuration option to build the dropdown by yourself and use the rowId parameter in this case. Here is the documentation about it http://gijgo.com/grid/configuration/column.renderer

If you want to use our inline editing functionality you can use the column.editor function in order to do that. Here is an example: https://github.com/atatanasov/gijgo/blob/master/examples/grid/Grid.InlineEditing.column.editor.Custom.With.Select2.html

**Comment by mmanna3** [comment]
That was exactly what I need, thank you very much!
