### ISSUE TITLE
gijgo@1.9.3/combined does not contain locales

### ISSUE THREAD

**Issue by bvn13** [atatanasov/gijgo#306]
Have tried to use Datepicker with locale 'ru-ru'. Error occured. I checked 'gijgo.min.js' file content - it does not contain locales! They all commented out. Why?

**Comment by atatanasov** [comment]
Yes. That's how it should be. Most of the javascript libraries are using locales from a separate files in the combined builds in order to make the combined js smaller. You need to include https://cdn.jsdelivr.net/npm/gijgo@1.9.3/combined/js/messages/messages.ru-ru.js in your case.

Here is the demo: http://gijgo.com/datepicker/example/localization
