### ISSUE TITLE
After search, the paging number won't back to page 1

### ISSUE THREAD

**Issue by jefferyleo** [atatanasov/gijgo#32]
![gijgo grid](https://cloud.githubusercontent.com/assets/6831609/20333996/9e434ae4-abf1-11e6-807d-31232ae62900.png)

Hi, I would like to ask, let say before I started to search any string, I went to page 2, but after I search with some random string, the result will show in page 1, but why the gigjo grid won't back to page 1 automatically instead of staying at page 2?

**Comment by atatanasov** [comment]
Hi,
You always need to specify in your request that you want to return to page 1. This is not done automatically. You can simply call grid.reload({ page:1, query: 'search value'});
Keep in mind that you always need specify records and totalCount in your response from the server in order to have correct paging.
