### ISSUE TITLE
Grid not reloading from ajax

### ISSUE THREAD

**Issue by MB34** [atatanasov/gijgo#321]
I have the following function with an ajax call that loads data from my API and the loads it into the grid named `ic_grid`.

If I attempt to reload the grid by calling this again, the **data HAS changed** but the grid will 
NOT load it, it shows empty.

Am I doing something wrong here?

    function GetP() 
    {
        $.ajax({
            method: "GET",
            url: "API/GetIC?yr=" + yr, 
            dataType: 'json',
            success: function( data ) {
                $("#p-flyout").hide();
                setDisabled($("#p_value"), true);
                if(typeof icgrid !== 'undefined') {
                    icgrid.hide();
                    icgrid.clear();
                } 
                icgrid = $('#ic_grid').grid({
                             primaryKey: 'ic',
                             dataSource: data,
                             uiLibrary: 'bootstrap4',
                             width: 717,
                             bodyRowHeight: 'fixed',
                             columns: [
                                 { field: 'app', title: 'App', sortable: true, headerCssClass: 'gridHeader' },
                                 { field: 'ic', title: 'ic', width: 150, sortable: true, headerCssClass: 'gridHeader' }
                             ],
                             pager: { limit: 10 }
                         });    
                icgrid.show();
            }
        });             
    }

**Comment by atatanasov** [comment]
I think that would be best if you create an instance of the grid on initialization of that page and use .render() in order to reload data into that grid. You can see an example at http://gijgo.com/grid/methods/render

The other option is to use .destroy() and then create a new instance of the grid.

Another useful example for you could be http://gijgo.com/grid/demos/connected-jquery-grids where we use remote data source.
