### ISSUE TITLE
grid - reset

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#86]
How I can comfortable clean all old search parameter in the internal memory of the grid without reload of the grid and reload the grid with new search inputs? I miss anayway a parameter by the reload method who make it possible to delete all old search parameter in the local storage ( or whereever you save this stuff).

**Comment by atatanasov** [comment]
I think that would be best to delete all old values on .reload() by setting them to undefined or blank (depends what would be best for you on the backend). I store them in grid.data().params, but it's not safe to manipulate them directly, because I may decide to change this in the future for some reason. I recommend the following code:

```
grid.reload({ param1: 'test' });
grid.reload({ param1: '', param2: 'test' });
```

p.s. In my projects I always have an extended reload method where I manage parameters. For example:

```
function reload(param1val, param2val) {
   grid.reload({ param1: param1val, param2: param2val });
}
```
